<a href="https://www.kaggle.com/code/fotimakhongulomova/pytorch-fundamentals?scriptVersionId=177189299" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# PyTorch Fundamentals 

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.2+cpu


### Introduction to Tensors

#### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` -= https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


In [3]:
# Vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [4]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
tensor([7, 8])
tensor([ 9, 10])
torch.Size([2, 2])


In [5]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 4],
                        [5, 3, 6],
                        [6, 3, 2]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0][1])

tensor([[[1, 2, 4],
         [5, 3, 6],
         [6, 3, 2]]])
3
torch.Size([1, 3, 3])
tensor([5, 3, 6])


### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represents the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [6]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor)
random_tensor.ndim

tensor([[0.8255, 0.6608, 0.1367, 0.9311],
        [0.2341, 0.1779, 0.0858, 0.2116],
        [0.3784, 0.6647, 0.8466, 0.3302]])


2

In [7]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colort channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zero and Ones

In [8]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Range of Tensors and Tensors-like

`torch.arange()` -> https://pytorch.org/docs/stable/generated/torch.arange.html

In [10]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros.dtype

torch.int64

### Tensor datatypes

**Note:** Tensors datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
* Tensors not right datatype
* Tensors nor right shape
* Tensors not on the right device

In [12]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                             dtype=None, # what datatype is the tensors (e.g float32, float16) 
                             device=None, # what device is your tensor on
                             requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor
float_32_tensor.dtype

torch.float32

In [13]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [14]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
* Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
* Tensors nor right shape - to get shape from a tensor, can use `tensor.shape`
* Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [15]:
# Create a tensor 
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7248, 0.1730, 0.3516, 0.9483],
        [0.7386, 0.8443, 0.5628, 0.2934],
        [0.0338, 0.5134, 0.2290, 0.6625]])

In [16]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.7248, 0.1730, 0.3516, 0.9483],
        [0.7386, 0.8443, 0.5628, 0.2934],
        [0.0338, 0.5134, 0.2290, 0.6625]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operation)

Tensor operation include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [17]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])

# Add 10
tensor + 10

tensor([11, 12, 13])

In [18]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [19]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [20]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [21]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multipliction

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html


There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting mateix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [22]:
# Element wise multiplication 
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [23]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: shape errors

In [24]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

# torch.matmul(tensor_A, tensor_B)

In [25]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a give tensor.

In [26]:
tensor_B.T, tensor_B

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]))

In [27]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [28]:
# The matrix multiplication operation works when `tensor_B` transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Muptiplying {tensor_A.shape}, @ {tensor_B.T.shape}")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Muptiplying torch.Size([3, 2]), @ torch.Size([2, 3])
Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


## Tensor Aggregation 

Finding the **min**, **max**, **mean**, **sum**, etc `torch.min()`, `torch.max()`, `torch.mean()`, `torch.sum()`

Finding the positional **min**, **max** `torch.argmin()`, `torch.argmax()`

In [29]:
# Create a tensor
z = torch.arange(0, 100, 10)
z, z.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [30]:
print(torch.min(z), z.min())
print(torch.max(z), z.max())
print(torch.mean(z.type(torch.float32)), z.type(torch.float32).mean()) # the `torch.mean()` requires a tensor of float32
print(torch.sum(z), z.sum())

tensor(0) tensor(0)
tensor(90) tensor(90)
tensor(45.) tensor(45.)
tensor(450) tensor(450)


In [31]:
print(z.argmin(), z[0])
print(z.argmax(), z[9])

tensor(0) tensor(0)
tensor(9) tensor(90)


## Reshaping, stacking, squesing, and unsquesing tensor
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeze - removes all `1` dimensions from a tensor
* Unsqueze - add a `1` dimensions to a target tensor
* Permute - return a view of the imput with dimensions permuted (swapped) in a certain way

In [32]:
x = torch.arange(1., 10.)
print(x, x.shape)

# Add an extra dimensions
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [33]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [34]:
z[:, 0] = 5
z, x # changing the z changes x 

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [35]:
# Stack tensors on top of each other
x0_stacked = torch.stack([x, x, x, x, x], dim=0)
x0_stacked, x0_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([5, 9]))

In [36]:
x1_stacked = torch.stack([x, x, x, x, x], dim=1)
x1_stacked, x1_stacked.shape

(tensor([[5., 5., 5., 5., 5.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.],
         [5., 5., 5., 5., 5.],
         [6., 6., 6., 6., 6.],
         [7., 7., 7., 7., 7.],
         [8., 8., 8., 8., 8.],
         [9., 9., 9., 9., 9.]]),
 torch.Size([9, 5]))

In [37]:
x_vstacked = torch.vstack([x, x, x, x, x])
x_vstacked, x_vstacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([5, 9]))

In [38]:
x_hstacked = torch.hstack([x, x, x, x, x])
x_hstacked, x_hstacked.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([45]))

In [39]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}\n")

# Removes all single dimensions from a target tensor
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [40]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}\n")

# Add a single dimensions to a target tensor
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [41]:
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute([2, 0, 1]) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_permuted.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([3, 224, 224])
New shape: torch.Size([3, 224, 224])


In [42]:
x_original[0, 0, 0] = 87622334
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(87622336.), tensor(87622336.))

## Indexing (Selecting data from tensors

Indexing with Pytorch is similar to indexing with NumPy

In [43]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [44]:
print(x[0], '\n')
print(x[0][0], '\n')
print(x[0][0][0], '\n')

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 

tensor([1, 2, 3]) 

tensor(1) 



In [45]:
# You can also use `:`
print(x[:, 0])
print(x[:, :, 1])
print(x[:, 1, 1])

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])


In [46]:
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & Numpy

* Data in NumPy, want in PyTorch -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [47]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [48]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [49]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [50]:
# Change the value of tensor, what will this do to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [51]:
# 3:45:23