<a href="https://www.kaggle.com/code/fotimakhongulomova/pytorch-fundamentals?scriptVersionId=173387748" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

## PyTorch Fundamentals 

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.2+cpu


### Introduction to Tensors

#### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` -= https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


In [3]:
# Vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [4]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
tensor([7, 8])
tensor([ 9, 10])
torch.Size([2, 2])


In [5]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 4],
                        [5, 3, 6],
                        [6, 3, 2]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0][1])

tensor([[[1, 2, 4],
         [5, 3, 6],
         [6, 3, 2]]])
3
torch.Size([1, 3, 3])
tensor([5, 3, 6])
