<a href="https://www.kaggle.com/code/fotimakhongulomova/pytorch-fundamentals?scriptVersionId=173702849" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

## PyTorch Fundamentals 

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.2+cpu


### Introduction to Tensors

#### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` -= https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


In [3]:
# Vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [4]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
tensor([7, 8])
tensor([ 9, 10])
torch.Size([2, 2])


In [5]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 4],
                        [5, 3, 6],
                        [6, 3, 2]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0][1])

tensor([[[1, 2, 4],
         [5, 3, 6],
         [6, 3, 2]]])
3
torch.Size([1, 3, 3])
tensor([5, 3, 6])


### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represents the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [6]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor)
random_tensor.ndim

tensor([[0.3779, 0.0763, 0.1373, 0.2861],
        [0.5732, 0.9070, 0.9641, 0.1355],
        [0.8070, 0.1356, 0.2757, 0.1711]])


2

In [7]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colort channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zero and Ones

In [8]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Range of Tensors and Tensors-like

`torch.arange()` -> https://pytorch.org/docs/stable/generated/torch.arange.html

In [10]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros.dtype

torch.int64

### Tensor datatypes

**Note:** Tensors datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
* Tensors not right datatype
* Tensors nor right shape
* Tensors not on the right device

In [12]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                             dtype=None, # what datatype is the tensors (e.g float32, float16) 
                             device=None, # what device is your tensor on
                             requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor
float_32_tensor.dtype

torch.float32

In [13]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [14]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
* Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
* Tensors nor right shape - to get shape from a tensor, can use `tensor.shape`
* Tensors not on the right device - to get device from a tensor, can use `tensor.device`
