<a href="https://www.kaggle.com/code/fotimakhongulomova/pytorch-fundamentals-exercises?scriptVersionId=182045108" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on `torch.Tensor`
* The documentation on `torch.cuda`

In [1]:
# No code solution (only reading)

### 2. Create a random tensor with shape (7, 7).

In [2]:
import torch
tensor = torch.rand(7, 7)
tensor

tensor([[0.1927, 0.8877, 0.8409, 0.6218, 0.5819, 0.3140, 0.9459],
        [0.3760, 0.8858, 0.7405, 0.6457, 0.7472, 0.6520, 0.4967],
        [0.4743, 0.1481, 0.1116, 0.2481, 0.5841, 0.2305, 0.1876],
        [0.1820, 0.0570, 0.4159, 0.0687, 0.2979, 0.6938, 0.8660],
        [0.1382, 0.9259, 0.8467, 0.2327, 0.9361, 0.1429, 0.5866],
        [0.7332, 0.8924, 0.6901, 0.8042, 0.8068, 0.2053, 0.9848],
        [0.1041, 0.0073, 0.2616, 0.3211, 0.3776, 0.2131, 0.9313]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [3]:
tensor_1 = torch.rand(1, 7)
tensor_1

tensor([[0.0482, 0.6190, 0.6045, 0.3642, 0.2833, 0.4498, 0.8049]])

In [4]:
tensor_mul = tensor.matmul(tensor_1.T)
tensor_mul, tensor_mul.shape

(tensor([[2.3612],
         [2.1540],
         [0.6925],
         [1.4141],
         [1.9781],
         [2.4115],
         [1.2371]]),
 torch.Size([7, 1]))

### 4. Set the random seed to 0 and do 2 & 3 over again.

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_a = torch.rand(7, 7)
tensor_b = torch.rand(1, 7)

# Matrix multiply tensors
tensor_ab = tensor_a.matmul(tensor_b.T)
print(f"Tensor_A: \n{tensor_a}, \nTensor_B: \n{tensor_b}, \nTensor_AB: \n{tensor_ab}")

Tensor_A: 
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]), 
Tensor_B: 
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]), 
Tensor_AB: 
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [6]:
torch.cuda.manual_seed(1234)

### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [7]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())

# Create two random tensors on GPU
tensor_c = torch.rand(2, 3).to("cuda")
tensor_d = torch.rand(2, 3).to("cuda")
print(f"Tensor_C: \n{tensor_c}, \nTensor_D: \n{tensor_d}")

True
Tensor_C: 
tensor([[0.5932, 0.1123, 0.1535],
        [0.2417, 0.7262, 0.7011]], device='cuda:0'), 
Tensor_D: 
tensor([[0.2038, 0.6511, 0.7745],
        [0.4369, 0.5191, 0.6159]], device='cuda:0')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [8]:
tensor_cd = tensor_c.matmul(tensor_d.T)
tensor_cd

tensor([[0.3129, 0.4120],
        [1.0651, 0.9143]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
max_tensor_cd = tensor_cd.max()

# Find min
min_tensor_cd = tensor_cd.min()
max_tensor_cd, min_tensor_cd

(tensor(1.0651, device='cuda:0'), tensor(0.3129, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
argmax_tensor_cd = torch.argmax(tensor_cd)

# Find arg min
argmin_tensor_cd = torch.argmin(tensor_cd)
argmax_tensor_cd, argmin_tensor_cd

(tensor(2, device='cuda:0'), tensor(0, device='cuda:0'))

### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [11]:
# Set seed
torch.cuda.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10).to("cuda")

# Remove single dimensions
tensor_sq = torch.squeeze(tensor)

# Print out tensors and their shapes
tensor.shape, tensor_sq.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))

In [12]:
tensor, tensor_sq

(tensor([[[[0.8102, 0.9801, 0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412,
            0.5995, 0.0652]]]], device='cuda:0'),
 tensor([0.8102, 0.9801, 0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995,
         0.0652], device='cuda:0'))